name: Android Reviews Import

on:
  schedule:
    - cron: '0 * * * *'   # todo início de hora (UTC)
  workflow_dispatch:      # permite rodar manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i
      - run: node index.mjs
        env:
          ANDROID_APP_ID: br.com.icatuseguros.appicatu
          WORKER_IMPORT_URL: https://reviews-bot.gabrielmtavares.workers.dev/api/import/android
          IMPORT_TOKEN: ${{ secrets.IMPORT_TOKEN }}
