name: Android Reviews Import
on:
  schedule:
    - cron: '35 * * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: node index.mjs
        env:
          ANDROID_APP_ID: br.com.icatuseguros.appicatu
          IMPORT_URL: ${{ secrets.IMPORT_URL }}
          IMPORT_TOKEN: ${{ secrets.IMPORT_TOKEN }}
