name: Android Reviews Import - main

on:
  workflow_dispatch:
  schedule:
    - cron: "10 * * * *"  # a cada 1h (10 min depois do Android)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies (lock-aware)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile=false
          elif [ -f yarn.lock ]; then
            corepack enable
            yarn install --frozen-lockfile
          elif [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            echo "No lockfile found. Running npm install..."
            npm install
          fi

      - name: Run importer
        env:
          ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
          WORKER_URL: ${{ secrets.WORKER_URL }}
          IMPORT_TOKEN: ${{ secrets.IMPORT_TOKEN }}
          ANDROID_PAGES: ${{ vars.ANDROID_PAGES || 2 }}
          LANG: ${{ vars.LANG || 'pt_BR' }}
          COUNTRY: ${{ vars.COUNTRY || 'br' }}
        run: |
          node index.mjs
